using System.ComponentModel.DataAnnotations;

namespace SENG302.Api.Models.Requests;

/** 
    A basic task list with a Name between 3 and 128 characters, 
    and an array of Tasks. The Id is auto-generated by the database.
*/
public class NewTaskListRequest
{

    [MaxLength(128)]
    public string Name { get; set; } = string.Empty;
    public string UserEmail { get; set; } = string.Empty;

}